docker: Add libusb-1.0-0 from apt
When running the whole application (including PortUpdater which scans
for connected devices), this error occured:

    usb.core.NoBackendError: No backend available

On Windows, the dependency "libusb_package" makes sure that the DLL is
present and usable. On Linux, the shared libraries are assumed to be
present on the system.

Installing libusb-1.0-0 is part of acconeer.exptool.setup, which new
users use to setup their PC.

Change-Id: I2b4a248e9e6866fff0d543a32d13584f4437fc9d